server:
  tomcat:
    threads:
      max: 100
    accept-count: 50
  port: ${PRODUCT_PORT}

service:
  pause: false

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,refresh,bus-refresh

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      maximumPoolSize: 10
      minimumIdle: 5
      validation-timeout: 10000
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_DEFAULTZONE}
